name: Zola

on:
  push:
    branches: main
  pull_request:

jobs:
  zola:
    runs-on: ubuntu-latest
    env:
      BASE_URL: https://github.com/getzola/zola/releases/download
      VERS: v0.15.2
      ARCH: x86_64-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v2
      - name: Install Zola
        run: curl -L ${BASE_URL}/${VERS}/zola-${VERS}-${ARCH}.tar.gz | tar -xz
      - run: ./zola --version
      - run: ./zola build
      - name: Deploy
        if: github.ref == 'refs/heads/main'
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: public
          fqdn: marcos.unsafe.rs
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
